

#include <string.h>
#include <string>

#ifndef PUBLICATIONPROCESSING_H
#define PUBLICATIONPROCESSING_H

using namespace std;

class PublicationProcessing {

public:
    PublicationProcessing(vector<vector<string>> data);

    //getters
    int getPublicationCounter ();
    int getPublishedCounter ();
    int getPublishedJournalArticleCounter ();
    vector<string> getPublishedJACEmp();
    int getPublishedBooksCounter ();
    vector<string> getPublishedBC();
    int getPublishedCasereportsCounter ();
    vector<string> getPublishedCRC();
    int getPublishedAbstractCounter ();
    vector<string> getPublishedAC();
    int getPublishedBookChaptersCounter ();
    vector<string> getPublishedBCC();
    int getPublishedJAMARCounter ();
    vector<string> getPublishedJAMAR();
    int getPublishedOSCounter ();
    vector<string> getPublishedOS();
    int getPublishedNewsArticleCounter ();
    vector<string> getPublishedNAC();
    int getPublishedWorkingPaperCounter ();
    vector<string> getPublishedWPC();
    int getPublishedSSPCounter ();
    vector<string> getPublishedSSP();
    int getPublishedMagaizeEntryCounter ();
    vector<string> getPublishedMEC();
    int getPublishedclinicalCareGuidelinesCounter ();
    vector<string> getPublishedCCG();
    int getPublishedNewsLetterArticleCounter ();
    vector<string> getPublishedNLAC();
    int getPublishedMultimediaCounter ();
    vector<string> getPublishedMC();
    int getPublishedInvitedArticlesCounter ();
    vector<string> getPublishedIA();
    int getPublishedCPCounter ();
    vector<string> getPublishedCPC();
    int getPublishedWebsiteVideoCounter ();
    vector<string> getPublishedWVC();
    int getPublishedMonographCounter ();
    vector<string> getPublishedM();
    int getPublishedManualCounter ();
    vector<string> getPublishedMCC();
    int getPublishedLetterstoEditorCounter ();
    vector<string> getPublishedLEC();
    int getPublishedEditorialCounter ();
    vector<string> getPublishedEC();
    int getPublishedCommentaryCounter ();
    vector<string> getPublishedC();
    int getPublishedBooksEditedCounter ();
    vector<string> getPublishedBE();
    int getPublishedGPCounter ();
    vector<string> getPublishedGP();
    int getAcceptedCounter ();
    int getAcceptedJournalArticleCounter ();
    vector<string> getAcceptedJACEmp();
    int getAcceptedBooksCounter ();
    vector<string> getAcceptedBC();
    int getAcceptedCasereportsCounter ();
    vector<string> getAcceptedCRC();
    int getAcceptedAbstractCounter ();
    vector<string> getAcceptedAC();
    int getAcceptedBookChaptersCounter ();
    vector<string> getAcceptedBCC();
    int getAcceptedJAMARCounter ();
    vector<string> getAcceptedJAMAR();
    int getAcceptedOSCounter ();
    vector<string> getAcceptedOS();
    int getAcceptedNewsArticleCounter ();
    vector<string> getAcceptedNAC();
    int getAcceptedWorkingPaperCounter ();
    vector<string> getAcceptedWPC();
    int getAcceptedSSPCounter ();
    vector<string> getAcceptedSSP();
    int getAcceptedMagaizeEntryCounter ();
    vector<string> getAcceptedMEC();
    int getAcceptedclinicalCareGuidelinesCounter ();
    vector<string> getAcceptedCCG();
    int getAcceptedNewsLetterArticleCounter ();
    vector<string> getAcceptedNLAC();
    int getAcceptedMultimediaCounter ();
    vector<string> getAcceptedMC();
    int getAcceptedInvitedArticlesCounter ();
    vector<string> getAcceptedIA();
    int getAcceptedCPCounter ();
    vector<string> getAcceptedCPC();
    int getAcceptedWebsiteVideoCounter ();
    vector<string> getAcceptedWVC();
    int getAcceptedMonographCounter ();
    vector<string> getAcceptedM();
    int getAcceptedManualCounter ();
    vector<string> getAcceptedMCC();
    int getAcceptedLetterstoEditorCounter ();
    vector<string> getAcceptedLEC();
    int getAcceptedEditorialCounter ();
    vector<string> getAcceptedEC();
    int getAcceptedCommentaryCounter ();
    vector<string> getAcceptedC();
    int getAcceptedBooksEditedCounter ();
    vector<string> getAcceptedBE();
    int getAcceptedGPCounter ();
    vector<string> getAcceptedGP();
    int getSubmittedCounter ();
    int getSubmittedJournalArticleCounter ();
    vector<string> getSubmittedJACEmp();
    int getSubmittedBooksCounter ();
    vector<string> getSubmittedBC();
    int getSubmittedCasereportsCounter ();
    vector<string> getSubmittedCRC();
    int getSubmittedAbstractCounter ();
    vector<string> getSubmittedAC();
    int getSubmittedBookChaptersCounter ();
    vector<string> getSubmittedBCC();
    int getSubmittedJAMARCounter ();
    vector<string> getSubmittedJAMAR();
    int getSubmittedOSCounter ();
    vector<string> getSubmittedOS();
    int getSubmittedNewsArticleCounter ();
    vector<string> getSubmittedNAC();
    int getSubmittedWorkingPaperCounter ();
    vector<string> getSubmittedWPC();
    int getSubmittedSSPCounter ();
    vector<string> getSubmittedSSP();
    int getSubmittedMagaizeEntryCounter ();
    vector<string> getSubmittedMEC();
    int getSubmittedclinicalCareGuidelinesCounter ();
    vector<string> getSubmittedCCG();
    int getSubmittedNewsLetterArticleCounter ();
    vector<string> getSubmittedNLAC();
    int getSubmittedMultimediaCounter ();
    vector<string> getSubmittedMC();
    int getSubmittedInvitedArticlesCounter ();
    vector<string> getSubmittedIA();
    int getSubmittedCPCounter ();
    vector<string> getSubmittedCPC();
    int getSubmittedWebsiteVideoCounter ();
    vector<string> getSubmittedWVC();
    int getSubmittedMonographCounter ();
    vector<string> getSubmittedM();
    int getSubmittedManualCounter ();
    vector<string> getSubmittedMCC();
    int getSubmittedLetterstoEditorCounter ();
    vector<string> getSubmittedLEC();
    int getSubmittedEditorialCounter ();
    vector<string> getSubmittedEC();
    int getSubmittedCommentaryCounter ();
    vector<string> getSubmittedC();
    int getSubmittedBooksEditedCounter ();
    vector<string> getSubmittedBE();
    int getSubmittedGPCounter ();
    vector<string> getSubmittedGP();

private:
    int publicationCounter = 0;
    int publishedCounter = 0;
    int publishedJournalArticleCounter = 0;
    vector<string> publishedJACEmp;
    int publishedBooksCounter = 0;
    vector<string> publishedBC;
    int publishedCasereportsCounter = 0;
    vector<string> publishedCRC;
    int publishedAbstractCounter = 0;
    vector<string> publishedAC;
    int publishedBookChaptersCounter = 0;
    vector<string> publishedBCC;
    int publishedJAMARCounter = 0;
    vector<string> publishedJAMAR;
    int publishedOSCounter = 0;
    vector<string> publishedOS;
    int publishedNewsArticleCounter = 0;
    vector<string> publishedNAC;
    int publishedWorkingPaperCounter = 0;
    vector<string> publishedWPC;
    int publishedSSPCounter = 0;
    vector<string> publishedSSP;
    int publishedMagaizeEntryCounter = 0;
    vector<string> publishedMEC;
    int publishedclinicalCareGuidelinesCounter = 0;
    vector<string> publishedCCG;
    int publishedNewsLetterArticleCounter = 0;
    vector<string> publishedNLAC;
    int publishedMultimediaCounter = 0;
    vector<string> publishedMC;
    int publishedInvitedArticlesCounter = 0;
    vector<string> publishedIA;
    int publishedCPCounter = 0;
    vector<string> publishedCPC;
    int publishedWebsiteVideoCounter = 0;
    vector<string> publishedWVC;
    int publishedMonographCounter = 0;
    vector<string> publishedM;
    int publishedManualCounter = 0;
    vector<string> publishedMCC;
    int publishedLetterstoEditorCounter = 0;
    vector<string> publishedLEC;
    int publishedEditorialCounter = 0;
    vector<string> publishedEC;
    int publishedCommentaryCounter = 0;
    vector<string> publishedC;
    int publishedBooksEditedCounter = 0;
    vector<string> publishedBE;
    int publishedGPCounter = 0;
    vector<string> publishedGP;

    int acceptedCounter = 0;
    int acceptedJournalArticleCounter = 0;
    vector<string> acceptedJACEmp;
    int acceptedBooksCounter = 0;
    vector<string> acceptedBC;
    int acceptedCasereportsCounter = 0;
    vector<string> acceptedCRC;
    int acceptedAbstractCounter = 0;
    vector<string> acceptedAC;
    int acceptedBookChaptersCounter = 0;
    vector<string> acceptedBCC;
    int acceptedJAMARCounter = 0;
    vector<string> acceptedJAMAR;
    int acceptedOSCounter = 0;
    vector<string> acceptedOS;
    int acceptedNewsArticleCounter = 0;
    vector<string> acceptedNAC;
    int acceptedWorkingPaperCounter = 0;
    vector<string> acceptedWPC;
    int acceptedSSPCounter = 0;
    vector<string> acceptedSSP;
    int acceptedMagaizeEntryCounter = 0;
    vector<string> acceptedMEC;
    int acceptedclinicalCareGuidelinesCounter = 0;
    vector<string> acceptedCCG;
    int acceptedNewsLetterArticleCounter = 0;
    vector<string> acceptedNLAC;
    int acceptedMultimediaCounter = 0;
    vector<string> acceptedMC;
    int acceptedInvitedArticlesCounter = 0;
    vector<string> acceptedIA;
    int acceptedCPCounter = 0;
    vector<string> acceptedCPC;
    int acceptedWebsiteVideoCounter = 0;
    vector<string> acceptedWVC;
    int acceptedMonographCounter = 0;
    vector<string> acceptedM;
    int acceptedManualCounter = 0;
    vector<string> acceptedMCC;
    int acceptedLetterstoEditorCounter = 0;
    vector<string> acceptedLEC;
    int acceptedEditorialCounter = 0;
    vector<string> acceptedEC;
    int acceptedCommentaryCounter = 0;
    vector<string> acceptedC;
    int acceptedBooksEditedCounter = 0;
    vector<string> acceptedBE;
    int acceptedGPCounter = 0;
    vector<string> acceptedGP;

    int submittedCounter = 0;
    int submittedJournalArticleCounter = 0;
    vector<string> submittedJACEmp;
    int submittedBooksCounter = 0;
    vector<string> submittedBC;
    int submittedCasereportsCounter = 0;
    vector<string> submittedCRC;
    int submittedAbstractCounter = 0;
    vector<string> submittedAC;
    int submittedBookChaptersCounter = 0;
    vector<string> submittedBCC;
    int submittedJAMARCounter = 0;
    vector<string> submittedJAMAR;
    int submittedOSCounter = 0;
    vector<string> submittedOS;
    int submittedNewsArticleCounter = 0;
    vector<string> submittedNAC;
    int submittedWorkingPaperCounter = 0;
    vector<string> submittedWPC;
    int submittedSSPCounter = 0;
    vector<string> submittedSSP;
    int submittedMagaizeEntryCounter = 0;
    vector<string> submittedMEC;
    int submittedclinicalCareGuidelinesCounter = 0;
    vector<string> submittedCCG;
    int submittedNewsLetterArticleCounter = 0;
    vector<string> submittedNLAC;
    int submittedMultimediaCounter = 0;
    vector<string> submittedMC;
    int submittedInvitedArticlesCounter = 0;
    vector<string> submittedIA;
    int submittedCPCounter = 0;
    vector<string> submittedCPC;
    int submittedWebsiteVideoCounter = 0;
    vector<string> submittedWVC;
    int submittedMonographCounter = 0;
    vector<string> submittedM;
    int submittedManualCounter = 0;
    vector<string> submittedMCC;
    int submittedLetterstoEditorCounter = 0;
    vector<string> submittedLEC;
    int submittedEditorialCounter = 0;
    vector<string> submittedEC;
    int submittedCommentaryCounter = 0;
    vector<string> submittedC;
    int submittedBooksEditedCounter = 0;
    vector<string> submittedBE;
    int submittedGPCounter = 0;
    vector<string> submittedGP;

};

#endif // PUBLICATIONPROCESSING_H
